$(document).ready(function() {
    $('svg path').on('click', function() {
        $(this).focus(); });
    var dens = {
        "Amnat Charoen":110.02,
        "Ang Thong": 284.50,
        "Bangkok Metropolis": 4059.02,
        "Bueng Kan":121.34,
        "Buri Ram":146.49,
        "Chachoengsao":118.27,
        "Chai Nat":144.57,
        "Chaiyaphum":85.85,
        "Chanthaburi":75.09,
        "Chiang Mai":67.85,
        "Chiang Rai":97.72,
        "Chon Buri":231.28,
        "Chumphon":75.69,
        "Kalasin":132.87,
        "Kamphaeng Phet":78.24,
        "Kanchanaburi":37.91,
        "Khon Kaen":163.03,
        "Krabi":69.27,
        "Lampang":62.45,
        "Lamphun":92.04,
        "Loei":56.92,
        "Lop Buri":119.98,
        "Mae Hong Son":16.44,
        "Maha Sarakham":167.54,
        "Mukdahan":73.68,
        "Nakhon Nayok":111.91,
        "Nakhon Pathom":382.24,
        "Nakhon Phanom":123.71,
        "Nakhon Ratchasima":124.55,
        "Nakhon Sawan":114.57,
        "Nakhon Si Thammarat":152.48,
        "Nan":37.38,
        "Narathiwat":148.13,
        "Nong Bua Lam Phu":119.07,
        "Nong Khai":121.34,
        "Nonthaburi":1260.53,
        "Pathum Thani":449.82,
        "Pattani":297.32,
        "Phangnga":59.37,
        "Phatthalung":132.88,
        "Phatthaya":231.28,
        "Phayao":81.70,
        "Phetchabun":77.98,
        "Phetchaburi":69.65,
        "Phichit":134.33,
        "Phitsanulok":75.28,
        "Phra Nakhon Si Ayutthaya":285.62,
        "Phrae":76.16,
        "Phuket":443.13,
        "Prachin Buri":83.18,
        "Prachuap Khiri Khan":70.26,
        "Ranong":50.50,
        "Ratchaburi":150.77,
        "Rayong":142.92,
        "Roi Et":160.03,
        "Sa Kaeo":70.16,
        "Sakon Nakhon":108.63,
        "Samut Prakan":1063.67,
        "Samut Sakhon":542.18,
        "Samut Songkhram":521.09,
        "Saraburi":162.68,
        "Satun":94.71,
        "Si Sa Ket":156.47,
        "Sing Buri":278.05,
        "Songkhla":159.91,
        "Sukhothai":89.36,
        "Suphan Buri":159.85,
        "Surat Thani":66.23,
        "Surin":150.18,
        "Tak":28.13,
        "Trang":125.00,
        "Trat":76.11,
        "Ubon Ratchathani":108.09,
        "Udon Thani":132.22,
        "Uthai Thani":45.64,
        "Uttaradit":58.63,
        "Yala":92.33,
        "Yasothon":135.97,

    }
    var dens1 = {
        "Amnat Charoen":1,
        "Ang Thong": 3,
        "Bangkok Metropolis": 2,
        "Bueng Kan":5,
        "Buri Ram":9,
        "Chachoengsao":6,
        "Chai Nat":2,
        "Chaiyaphum":5,
        "Chanthaburi":7,
        "Chiang Mai":12,
        "Chiang Rai":18,
        "Chon Buri":7,
        "Chumphon":4,
        "Kalasin":5,
        "Kamphaeng Phet":7,
        "Kanchanaburi":9,
        "Khon Kaen":6,
        "Krabi":3,
        "Lampang":8,
        "Lamphun":4,
        "Loei":6,
        "Lop Buri":6,
        "Mae Hong Son":10,
        "Maha Sarakham":6,
        "Mukdahan":7,
        "Nakhon Nayok":5,
        "Nakhon Pathom":2,
        "Nakhon Phanom":7,
        "Nakhon Ratchasima":9,
        "Nakhon Sawan":5,
        "Nakhon Si Thammarat":4,
        "Nan":9,
        "Narathiwat":2,
        "Nong Bua Lam Phu":5,
        "Nong Khai":5,
        "Nonthaburi":4,
        "Pathum Thani":2,
        "Pattani":3,
        "Phangnga":2,
        "Phatthalung":5,
        "Phatthaya":7,
        "Phayao":6,
        "Phetchabun":9,
        "Phetchaburi":6,
        "Phichit":1,
        "Phitsanulok":5,
        "Phra Nakhon Si Ayutthaya":5,
        "Phrae":9,
        "Phuket":3,
        "Prachin Buri":5,
        "Prachuap Khiri Khan":4,
        "Ranong":1,
        "Ratchaburi":7,
        "Rayong":7,
        "Roi Et":9,
        "Sa Kaeo":5,
        "Sakon Nakhon":7,
        "Samut Prakan":5,
        "Samut Sakhon":3,
        "Samut Songkhram":1,
        "Saraburi":7,
        "Satun":5,
        "Si Sa Ket":2,
        "Sing Buri":3,
        "Songkhla":5,
        "Sukhothai":8,
        "Suphan Buri":9,
        "Surat Thani":6,
        "Surin":8,
        "Tak":10,
        "Trang":6,
        "Trat":5,
        "Ubon Ratchathani":4,
        "Udon Thani":6,
        "Uthai Thani":5,
        "Uttaradit":3,
        "Yala":2,
        "Yasothon":4,

    }
    // Select the path element with id
    $('.province').on('click', function() {
        // Set the text of the element with id "displayName"
        var province = $(this).attr('name');
        $('.displayName').text(province);
        console.log(dens[province])
        $('.displaydens').text(dens[province]);
        $('.displaydens1').text(dens1[province]);
    })

    $('.reclegend').on('click', function() {
        // Set the text of the element with id "displayName"
        var reclegend = $(this).attr('name');
        $('.displayName').text(reclegend);
});});
